version: '3.8'

services:
  # Redis for local caching and agent memory
  redis:
    image: redis:7-alpine
    container_name: rate-lock-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rate-lock-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  rate-lock-network:
    driver: bridge
